[package]
name = "ruffle_render_wgpu"
authors = ["Nathan Adams <dinnerbone@dinnerbone.com>"]
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wgpu = { version = "0.15.1", features = ["naga"] }
tracing = "0.1.37"
ruffle_render = { path = "..", features = ["tessellator"] }
bytemuck = { version = "1.13.1", features = ["derive"] }
raw-window-handle = "0.5"
clap = { version = "4.1.8", features = ["derive"], optional = true }
enum-map = "2.4.2"
fnv = "1.0.7"
swf = { path = "../../swf" }
image = { version = "0.24.5", default-features = false }
naga_oil = "0.5.0"
ouroboros = "0.16.0"
typed-arena = "2.0.2"
once_cell = "1.17.1"
gc-arena = { workspace = true }
naga-agal = { path = "../naga-agal" }
downcast-rs = "1.2.0"
profiling = { version = "1.0", default-features = false, optional = true }
naga = { version = "0.11.0", features = ["validate", "wgsl-out"] }

# desktop
[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.26"

# wasm
[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3.61"
features = ["HtmlCanvasElement"]

[features]
render_debug_labels = []
render_trace = ["wgpu/trace"]
webgl = ["wgpu/webgl"]
profile-with-tracy = ["profiling", "profiling/profile-with-tracy"]
